### ISSUE TITLE
String Bug?

### ISSUE THREAD

**Issue by RhianNoobie** [rudes/PokeStrings#3]
Hello i would like some help how to fix this bug or  unknown happening in this string pls

![Screenshot (12)](https://github.com/rudes/PokeStrings/assets/144241475/2022f19a-7eb8-4bce-962c-3530abb1f52b)

**Comment by rudes** [comment]
You need to either remove former strings you've installed or make sure you installed the placeholder file, revisit the install instructions and follow them closely.
