### ISSUE TITLE
Two of the files mess up item descriptions

### ISSUE THREAD

**Issue by henrychess** [rudes/PokeStrings#5]
The files are `zz_strings_en_PokeStrings_IRB_0.xml` and `zz_strings_en_PokeStrings_nds_Unova.xml`

If I import any of these files, the item descriptions become the same as the base game. If I import all other files but not these two, the item descriptions are good.

Images:
With these files (wrong description)
![Screenshot_20240211_083158_PokeMMO](https://github.com/rudes/PokeStrings/assets/91649568/544bcccc-a883-4938-912d-6b2aafb94f9a)
Without these files (correct description)
![Screenshot_20240211_083415_PokeMMO](https://github.com/rudes/PokeStrings/assets/91649568/32ccc155-7295-4663-a7e8-00bdf5223dff)

**Comment by rudes** [comment]
This strings pack is dead you should just grab Bill's strings, should be able to find a video or forum post covering them. I dont play the game and haven't really played it since before Johto released.
